/*
 * The MIT License
 *
 * Copyright 2011 Mike Kent.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package Leaderboard;

/*
 * LeaderboardPanel.java
 *
 * Created on Nov 30, 2011, 4:24:21 PM
 */


import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;

/**
 *
 * @author Mike Kent
 */
public class LeaderboardPanel extends javax.swing.JPanel
    implements MouseMotionListener
{

  private int mx, my;  // mouse coordinates

  /** Creates new form LeaderboardPanel */
  public LeaderboardPanel() {
    initComponents();
    this.addMouseMotionListener(this);
  }

  @Override
  public void repaint() {
    Graphics2D g = (Graphics2D)this.getGraphics();
    if(g == null) {
      System.out.println("g is null yo!!!");
      return;
    }
    Rectangle bounds = this.getBounds();
    g.fillRect(0, 0, bounds.width, bounds.height);
    //g.clearRect(0, 0, bounds.width, bounds.height);
    g.setPaint(new GradientPaint(mx-50, my-50, new Color(70, 143, 240),
        mx+50, my+50, new Color(175, 203, 240)));
    g.fillOval(mx-50, my-50, 100, 100);
  }

  public void mouseMoved(MouseEvent e) {
    mx = e.getX();
    my = e.getY();
    this.repaint();
  }

  public void mouseDragged(MouseEvent e) {
    // do nothing
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
